services:
  - type: web
    name: cardio-clash-backend
    runtime: docker
    plan: free
    rootDir: backend
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: cardio-clash-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cardio-clash-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: cardio-clash-db
          property: database
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: cardio-clash-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: cardio-clash-db
          property: password

databases:
  - name: cardio-clash-db
    databaseName: ecg_db
    user: ecg_user
    plan: free
